name: Node.js CI

on:
  pull_request:
    branches: 
      - development
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        SALT_ROUNDS: 1
        JWT_TOKEN: testing
